### ISSUE TITLE
catkin build error "franka_human_friendly_controllers"

### ISSUE THREAD

**Issue by Takahashi-Rei** [franzesegiovanni/franka_human_friendly_controllers#1]
Hi, I am having trouble building "franka_human_friendly_controllers".
The image below shows the error.
![Screenshot from 2022-09-26 17-25-49](https://user-images.githubusercontent.com/65320442/192229289-66d5a29a-4e09-446f-ac43-16a96c441560.png)
![Screenshot from 2022-09-26 17-26-12](https://user-images.githubusercontent.com/65320442/192229337-d305c5a9-7968-4c76-b213-f5b26e980bf7.png)
It seems to warn that "franka_gripper_online" is not found when building, but I don't know how to fix it.

The version of ros is noetic
The version of libfranka is 0.9.0
The version of franka_ros is 0.9.1

Do you know how to solve this problem?

best regards.

**Comment by franzesegiovanni** [comment]
Hi, have you also tried catkin_make?

catkin_make -DMAKE_BUILD_TYPE=Release -DFranka_DIR:PATH=~/libfranka/build

**Comment by Takahashi-Rei** [comment]
No I have not.
I am using "catkin-tools" to build "catkin_ws" and cannot use "catkin_make".
I will try some more and if it doesn't work, I will re-create "catkin_ws".

Thanks

**Comment by Takahashi-Rei** [comment]
Hi, I am reporting that I was able to rewrite part of the "CMakeList.txt" and get the build to pass. (comment out "franka_gripper" in lines 95 and 100)

The purpose of the build was to make the "ILoSA" program work, and it did.
I will close the issue.

Thank you!

**Comment by franzesegiovanni** [comment]
Hi, 

I was going to suggest that you could delete the compilation of the gripper node. That node is useful if you want to open and close the gripper with online commands from MATLAB or Python. It is strange to me that it does not work with catkin build. I will investigate more. Thank you for pointing it out and have fun with ILoSA :)
