### ISSUE TITLE
Why no gravity term when computing tau?

### ISSUE THREAD

**Issue by xianyitiantim** [franzesegiovanni/franka_human_friendly_controllers#3]
Hello, may I know why there is no gravity term when computing 'tau_d'? 

This term is added by tau_d << tau_task + tau_nullspace + coriolis+ tau_joint_limit;, which are from Cartesian PD control, nullspace PD control, the coriolis effect, and the joint limit effect.

Could you please explain that? Thank you.

**Comment by franzesegiovanni** [comment]
Hi, the gravity is compensated by default in the panda low-level controller. 

Regards,

Giovanni

**Comment by xianyitiantim** [comment]
Hi @franzesegiovanni , thanks for your answer! Now I got it!
