### ISSUE TITLE
Are there any plans to port to ROS2?

### ISSUE THREAD

**Issue by Ekanshh** [franzesegiovanni/franka_human_friendly_controllers#6]
Thank you for all your hard work on this project! :100:

I was wondering if there are any plans to port this work to ROS2? If not, what modifications would be necessary to use it with ROS2?

**Comment by franzesegiovanni** [comment]
Hi Ekanshh, 

Thank you for appreciating the human-friendly controllers. 

For the moment we do not have plans to switch. However, a new version for ros2 could be generated sometime at the end of the year. I will keep you posted. Please let me know if I can support you with anything or issues when using my controllers.
